name: Build Codicons

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build fonts
        run: npm run build
